### ISSUE TITLE
kubie exec command provides no error message if context is not setup

### ISSUE THREAD

**Issue by SEANDOUGHTY** [kubie-org/kubie#63] opened 2021-02-26 23:01 UTC
For example if you run `kubie exec random random echo random` there will be shell output informing the user that the context does not exist.

This would be a nice QoL improvement for debugging scripts that use the `kubie exec` command.

**Comment by sbstp** [comment] 2021-03-06 18:46
Hey thanks for reporting this! We'll have a fix for this in the next week or so.

**Comment by sbstp** [comment] 2021-03-07 18:31
Hey Sean, the issue is fixed and I've released kubie `0.13.2` for monday.

**Closed as completed** 2021-03-07 21:50 UTC

**Comment by SEANDOUGHTY** [comment] 2021-03-08 05:02
Hey Simon! Thanks so much for addressing this.
